---
title: "Lab 11"
author: "Adam Hayes, Erin Omyer, Richard Park, Jasmine Sanchez"
date: "4/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Adam's Findings

```{r}
library(tidyverse)
library(babynames)

data <- babynames

names <- babynames %>%
  group_by(year)%>%
  summarise(total = sum(n))

ada <- babynames %>%
  filter(str_detect(name, "^Ada"))%>%
  group_by(year)%>%
  summarise(num_ada = sum(n))

ada2 <- babynames %>%
  filter(str_detect(name, "^Adam$"))%>%
  group_by(year)%>%
  summarise(num_adam = sum(n))

newdata <- ada %>%
  left_join(names, by = "year")%>%
  mutate(prop = num_ada / total)

newnewdata <- newdata %>%
  left_join(ada2, by = "year") %>%
  mutate(prop_adam = num_adam / total)

ggplot(data = newnewdata)+
  geom_line(mapping = aes(x = year, y = prop), color = "red")+
  geom_line(mapping = aes(x = year, y = prop_adam))+
  labs(title = "Prop of names starting with Ada(red) and babies named Adam(black) by year")
```

### Richard's Findings

```{r}
library(tidyverse)
library(babynames)

data <- babynames

NamesRIC <- babynames %>%
  filter(str_detect(name, "^Ric") == T)

NamesRIC

PropName <- babynames %>%
  group_by(year) %>%
  summarise(number = sum(n))

PropRIC <- babynames %>%
  group_by(year) %>%
  filter(str_detect(name, "^Ric") == T) %>%
  summarise(number_RIC = sum(n))

PropRIC2 <- babynames %>%
  filter(str_detect(name, "^Richard$"))%>%
  group_by(year)%>%
  summarise(number_RICHARD = sum(n))


Newnamedata <- PropRIC %>%
  left_join(PropName, by = "year") %>%
  mutate(prop = number_RIC / number)

Newnamesdata <- Newnamedata %>%
  left_join(PropRIC2, by = "year") %>%
  mutate(proportion_Richard = number_RICHARD / number)

ggplot(data = Newnamesdata)+
  geom_point(mapping = aes(x = year, y = prop), color = "Blue")+
  geom_point(mapping = aes(x = year, y = proportion_Richard),color = "Red")+
  labs(title = "The Proportion of names that start with Ric(in blue) and babies named Richard(in red) by each year")
  
```